channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - filelock=3.13.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - ld_impl_linux-64=2.38
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.8.1.2
  - libcurand=10.3.4.107
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.1
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openssl=3.0.12
  - pip=23.3.1
  - python=3.10.13
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=2.0.0
  - torchtriton=2.0.0
  - typing_extensions=4.9.0
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - aiofiles==23.2.1
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - alembic==1.13.1
      - altair==5.2.0
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.2.0
      - asteroid-filterbanks==0.4.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - audioread==3.0.1
      - av==10.0.0
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.8.2
      - contourpy==1.2.0
      - ctranslate2==3.24.0
      - cycler==0.12.1
      - decorator==5.1.1
      - docopt==0.6.2
      - einops==0.7.0
      - exceptiongroup==1.2.0
      - fastapi==0.109.0
      - faster-whisper==0.10.0
      - ffmpy==0.3.1
      - flatbuffers==23.5.26
      - fonttools==4.47.2
      - frozenlist==1.4.1
      - fsspec==2023.12.2
      - gradio==4.16.0
      - gradio-client==0.8.1
      - greenlet==3.0.3
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - huggingface-hub==0.20.3
      - humanfriendly==10.0
      - hyperpyyaml==1.2.2
      - idna==3.6
      - importlib-resources==6.1.1
      - joblib==1.3.2
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - julius==0.2.7
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - librosa==0.10.1
      - lightning==2.1.3
      - lightning-utilities==0.10.1
      - llvmlite==0.41.1
      - mako==1.3.0
      - markdown-it-py==3.0.0
      - matplotlib==3.8.2
      - mdurl==0.1.2
      - msgpack==1.0.7
      - multidict==6.0.4
      - nltk==3.8.1
      - numba==0.58.1
      - omegaconf==2.3.0
      - onnxruntime==1.16.3
      - optuna==3.5.0
      - orjson==3.9.12
      - packaging==23.2
      - pandas==2.2.0
      - pillow==10.2.0
      - platformdirs==4.1.0
      - pooch==1.8.0
      - primepy==1.3
      - protobuf==4.25.2
      - pyannote-audio==3.1.1
      - pyannote-core==5.0.0
      - pyannote-database==5.0.1
      - pyannote-metrics==3.2.1
      - pyannote-pipeline==3.0.1
      - pycparser==2.21
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pydub==0.25.1
      - pygments==2.17.2
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-multipart==0.0.6
      - pytorch-lightning==2.1.3
      - pytorch-metric-learning==2.4.1
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - referencing==0.33.0
      - regex==2023.12.25
      - requests==2.31.0
      - rich==13.7.0
      - rpds-py==0.17.1
      - ruamel-yaml==0.18.5
      - ruamel-yaml-clib==0.2.8
      - ruff==0.1.14
      - safetensors==0.4.2
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - semantic-version==2.10.0
      - semver==3.0.2
      - sentencepiece==0.1.99
      - shellingham==1.5.4
      - six==1.16.0
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - soundfile==0.12.1
      - soxr==0.3.7
      - speechbrain==0.5.16
      - sqlalchemy==2.0.25
      - starlette==0.35.1
      - tabulate==0.9.0
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.2.0
      - tokenizers==0.15.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch-audiomentations==0.11.0
      - torch-pitch-shift==1.2.4
      - torchmetrics==1.3.0.post0
      - tqdm==4.66.1
      - transformers==4.37.2
      - typer==0.9.0
      - tzdata==2023.4
      - urllib3==2.1.0
      - uvicorn==0.27.0
      - websockets==11.0.3
      - whisperx==3.1.1
      - yarl==1.9.4
