channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pip=23.3.1
  - python=3.10.13
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - torchaudio=2.0.0
  - pip:
      - ctranslate2==4.0.0
      - faster-whisper==1.0.0
      - gradio==4.37.2
      - gradio-client==1.0.2
